apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntechlab-mock
  labels:
    app: ntechlab-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntechlab-mock
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ntechlab-mock
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ntechlab-mock
          image: cameritegeneric.azurecr.io/ntechlab-mock:latest
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: 80m
              memory: 250Mi
            limits:
              cpu: 1200m
              memory: 1024Mi
