apiVersion: v1
kind: Service
metadata:
  name: ntechlab-mock-internal-svc
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 5000
  selector:
    app: ntechlab-mock
